export const GET_DEPENDENCY = 'GET_DEPENDENCY';
export const GET_DEPENDENCY_SUCCESS = 'GET_DEPENDENCY_SUCCESS';
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS';
export const CLAER_PACKAGES_DEPENDENCY = 'CLAER_PACKAGES_DEPENDENCY';
